services:
  apache:
    build:
      context: images
      dockerfile: Php_Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      local_db:
        condition: service_healthy
  
  local_db:
    build:
      context: images
      dockerfile: MySQL_Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - sqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  sqldata: